services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bub
    env_file:
      - .env
    environment:
      BUB_HOME: /data
    volumes:
      - ${BUB_WORKSPACE_PATH:-.}:/workspace
      - ${BUB_HOME_HOST:-${HOME}/.bub}:/data
      - ${BUB_AGENT_HOME:-${HOME}/.agents}:/home/nonroot/.agents
      - "${HOME}/.codex/:/home/nonroot/.codex/"
      - "${HOME}/.config/opencode/:/home/nonroot/.config/opencode/"
      - "${HOME}/.local/share/opencode/:/home/nonroot/.local/share/opencode/"
      - "${HOME}/.local/state/opencode/:/home/nonroot/.local/state/opencode/"
      - "${HOME}/.opencode/:/home/nonroot/.opencode/"
      - ${BUB_HOME_HOST:-${HOME}/.bub}/wechat_token.json:/home/nonroot/.bub/wechat_token.json
    stdin_open: true
    tty: true
    restart: unless-stopped
